// Static portfolio data — used as a fallback when the Payload DB is unreachable
// (e.g. DB-independent builds). Screenshots are generated by
// scripts/capture-screenshots.js into public/projects/{name}.png.

export type PortfolioCategory = "Web" | "iOS" | "Android" | "Desktop" | "ERP";

export type PortfolioItem = {
  /** slug + screenshot filename (public/projects/{name}.png) */
  name: string;
  title: string;
  /** live site URL, also shown in the browser-frame address bar */
  url: string;
  image: string;
  category: PortfolioCategory;
  description: string;
  tags?: string[];
};

export const PORTFOLIO: PortfolioItem[] = [
  {
    name: "ddotsmediajobs",
    title: "Ddotsmedia Jobs",
    url: "https://ddotsmediajobs.com",
    image: "/projects/ddotsmediajobs.png",
    category: "Web",
    description:
      "Recruitment platform connecting UAE employers with talent — listings, profiles, and applicant tracking.",
    tags: ["Next.js", "Search", "Dashboards"],
  },
  {
    name: "ddotsmediaerp",
    title: "Ddotsmedia ERP",
    url: "https://ddotsmediaerp.com",
    image: "/projects/ddotsmediaerp.png",
    category: "ERP",
    description:
      "End-to-end ERP for inventory, sales, HR, and accounting with role-based dashboards and reporting.",
    tags: ["ERP", "Reporting", "Automation"],
  },
  {
    name: "ayurconnect",
    title: "AyurConnect",
    url: "https://ayurconnect.com",
    image: "/projects/ayurconnect.png",
    category: "Web",
    description:
      "Ayurveda wellness platform linking practitioners and patients with online booking and consultations.",
    tags: ["Booking", "Health", "Web"],
  },
  {
    name: "gayathi",
    title: "Gayathi",
    url: "https://gayathi.ae",
    image: "/projects/gayathi.png",
    category: "Web",
    description:
      "Corporate website for a UAE trading and services group with a CMS-driven catalogue.",
    tags: ["Branding", "CMS", "Web"],
  },
  {
    name: "ddotshop",
    title: "Ddotshop",
    url: "https://ddotshop.com",
    image: "/projects/ddotshop.png",
    category: "Web",
    description:
      "Modern e-commerce storefront with product catalogue, cart, and secure checkout.",
    tags: ["E-commerce", "Cart", "Payments"],
  },
  {
    name: "milisauh",
    title: "Milisa UH",
    url: "https://milisauh.ae",
    image: "/projects/milisauh.png",
    category: "Web",
    description:
      "Business website with service catalogue and online bookings for a UAE brand.",
    tags: ["Web", "Bookings", "CMS"],
  },
];
